# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec6c52984995730199d5dd84985aa663cd21d51b0688781242d3c825e106c1bab5a9ea55ab0d4df56234cd6576c5289cbff1fdea2abef27ee3a6d482b685e40b

test:
  secret_key_base: 1b2e3d85f5a4e153d45eb237be6f0ed58e77e1d8480e365c484073f37244d39b95ae088d665bd44a72777ea6cd3bbdeb69089b0c27e66409d48791fb6b5d5f5c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
